<a href="https://colab.research.google.com/github/Razia-Amy/AI-project/blob/main/spam_detect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Description: This program detects if an email spam (1) or not .(0).

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#Load the data
from google.colab import files
uploaded = files.upload()


Saving emails.csv to emails.csv


In [ ]:
#Read the CSV file
df = pd.read_csv('emails.csv')

#Print the first 5 rows of data
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
#Print the shape(Get the number of rows and columns)
df.shape

(5572, 2)

In [ ]:
#Get the columns name
df.columns

Index(['Label', 'EmailText'], dtype='object')

In [ ]:
#Check for duplicated and remove them
df.drop_duplicates(inplace = True)

In [ ]:
#Show the new shape(number of row and columns)
df.shape

(5169, 2)

In [ ]:
#Show the number of missing(NAN, NaN, na) data for each column
df.isnull().sum()

Label        0
EmailText    0
dtype: int64

In [ ]:
#Download the stopwords package
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):

  #1 remove punctuation
  #2 remove stopwords
  #3 return a list of clean text words

  #1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [ ]:
#Show the tokenization(a list of token also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [ ]:
#Examples

message4 = 'hello world hello world'
message5 = 'test test test test one'
print(message4)
print()

#Convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]] )
print(bow4)

print(bow4.shape)

hello world hello world

  (0, 0)	2
  (0, 3)	2
  (1, 2)	4
  (1, 1)	1
(2, 4)


In [ ]:
#Convert a collection of text to a matriz of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
#Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state=0)


In [ ]:
#Get the shape of messages_bow
messages_bow.shape


(5728, 37229)

In [ ]:
#Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

#Print the predictions
print(classifier.predict(X_train))

#Print the actual values
print(y_train.values)

[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]


In [ ]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: ', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3475
           1       0.99      1.00      1.00      1107

    accuracy                           1.00      4582
   macro avg       1.00      1.00      1.00      4582
weighted avg       1.00      1.00      1.00      4582


Confusion Matrix: 
 [[3466    9]
 [   2 1105]]

Accuracy:  0.9975993016150153


In [ ]:
#Print the predictions
print(classifier.predict(X_test))

#Print the actual values
print(y_test.values)

[0 0 1 ... 1 0 1]
[0 0 1 ... 0 0 1]


In [ ]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: ', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       885
           1       0.95      0.99      0.97       261

    accuracy                           0.99      1146
   macro avg       0.97      0.99      0.98      1146
weighted avg       0.99      0.99      0.99      1146


Confusion Matrix: 
 [[872  13]
 [  2 259]]

Accuracy:  0.9869109947643979
